app = 'cellguard-demo'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/release-gate/check?shard=shard-default'
    [checks.status.headers]
      Accept = 'application/json'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'

[[mounts]]
  source = 'cellguard_data'
  destination = '/rails/storage'

[processes]
  app = './bin/rails server'
  worker = 'bundle exec sidekiq -C config/sidekiq.yml'
